# Generated by Django 5.0.6 on 2024-06-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_count',
            field=models.IntegerField(),
        ),
    ]
